/*

      / / / / / / / / /
    / / wordell.h / /
  / / / / / / / / /

         2026
        mpower

*/

#ifndef WORDELL_H
#define WORDELL_H

/* string table constants
*/
#define IDSNAME       100
#define IDSABOUT      200
#define IDSTITLE      300

/* About dialog resource id
*/
#define ABOUTBOX        1

/* application icon resource id
*/
#define WORDELLICON     1

#endif
